### ISSUE TITLE
JOSS Review: Documentation

### ISSUE THREAD

**Issue by rabdill** [henrikdvn/CRSocket#1]
Hello! I'm one of the reviewers for this submission to JOSS, working on https://github.com/openjournals/joss-reviews/issues/5658. I don't mean to spam you with issues and comments, but I tried to split up my feedback into relevant chunks for discussion and will be submitting them as they come up. This issue has my notes about the "Documentation" section of the [JOSS reviewer checklist](https://joss.readthedocs.io/en/latest/review_checklist.html). (One minor note: The repository's readme currently has two links to documentation, one at `https://henrikdvn.github.io/CRSocket/` and one at `https://neurolab.no/docs/crsocket/`, which are slightly different. I reviewed the version at the first URL, which I believe is connected directly to the repository.)

>Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

The "CommTest" app appears to be a thorough demonstration of CRSocket's functionality, with lots of visibility into what's going on internally and [some documentation](https://henrikdvn.github.io/CRSocket/apps/CommTest.html) of what is being displayed. I think this would work fine for someone tinkering with the code who wanted to verify they hadn't broken anything, but I don't believe it's adequately documented to do this. I'm confident a CRSocket expert could use this for all kinds of things, but the controller and responder dashboards both include dozens of esoteric phrases without a description in the docs—the toggles for "Log," "Buf" and "Itc," for example.

If the CommTest app is meant to validate the functionality of the software, I believe it needs at least some of these additions to make it fit for purpose:

- An explanation of what all of the sections and line items are documenting.
- Instructions for initializing the application
- Recommended interactions to exercise different functionality
- Expected state. For example, on loading the Commtest Responder from the project homepage, the "receiverState" field is listed as "closed," and the "senderState" field is blank. I assume this is expected, but I don't actually know. It would be very helpful to have a list of actions and how this information is expected to change in response.

It's fine by me if the CommTest app isn't actually intended to be for testing the software, but in that case, another approach for validating functionality would be needed.

>Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

As far as I can tell, this is currently missing from the repository and documentation website. For what it's worth, GitHub made [an example `CONTRIBUTING.md` document](https://github.com/github/docs/blob/5a827cbdaa69a709dd2ab62ae0cdf0dbaca240b3/CONTRIBUTING.md) that may be helpful.

**Comment by henrikdvn** [comment]
Thanks for engaging with this, and feel free to give me all types of feedback. I will try to sort things out as fast as I can.

Regarding documentation differences: I have been working on some updates (mostly internal crosslinks and formatting) and wanted to complete them before committing. Anyways they should be in sync now.

I see your point regarding the CommTest app. I tried to compress the layout as much as possible so that it would be reasonably usable on mobile devices. Will try to incorporate your suggestions into the documentation, add some links from keywords in the app to other parts of the docs and possibly group different parts of the app into meaningful sections.

Regarding community guidelines: Thanks for the example. I'm not an expert on this. Will take a look at it and provide some guidelines.

**Comment by rabdill** [comment]
Sounds good to me! I hadn't considered making the layout mobile-friendly, but that makes a lot of sense, as does your proposed solution. I only mention the community guidelines because it's part of the review criteria—I realize it's probably more involved than necessary for projects that don't have a big community working on it already, but it could at least be helpful to answer basic questions such as "How do I tell the authors about a bug I've encountered?" or "How should I submit a proposed change?" There are lots of guides and examples online for [codes of conduct](https://opensource.guide/code-of-conduct/) and ["contributor covenants,"](https://opensource.google/documentation/reference/releasing/template/CODE_OF_CONDUCT) but, at least from my perspective, the JOSS requirements don't call for anything so extensive.

**Comment by henrikdvn** [comment]
I have now made the CommTest app a bit more user-friendly by adding descriptive title attributes (shown when moving the cursor above headings etc.),  and adding info links to relevant documentation. Have also added some simple contribution guidelines and provided more precise version info in the Installation documentation.

**Comment by henrikdvn** [comment]
Hope all issues have been resolved
